# =============================================================================
# SCENE SWITCHES PACKAGE
# =============================================================================
# File: packages/scene_switches.yaml
# Revision: 4.0
# Created: 2026-01-29
# Updated: 2026-01-29
#
# NOTE: Kitchen downlights use helper-based state tracking because the
#       Mercator lights report incorrect state (says ON when physically OFF)
#
# KITCHEN (kitchen_scene_switch_3g - TS0043 3-button):
#   Button 1: Bench downlights toggle - 100%, 3000K, 3s fade
#   Button 2: Ceiling light toggle - 100%, 6535K, 3s fade
#   Button 3: Sink downlight toggle - 100%, 6535K, 3s fade
#
# DINING (Dining Scene Switch – 1G - TS0041 1-button):
#   Single: Toggle - Whites 75%/2702K, Rings 100%/3400K
#   Double: Bright - Whites 100%/3200K, Rings 100%/3400K
#   Hold:   Party - Whites 100%/2702K, Rings GREEN
# =============================================================================

# =============================================================================
# HELPERS - Track intended state for unreliable Mercator lights
# =============================================================================
input_boolean:
  kitchen_bench_lights_on:
    name: "Kitchen Bench Lights Intended State"
    icon: mdi:lightbulb
  kitchen_sink_light_on:
    name: "Kitchen Sink Light Intended State"
    icon: mdi:lightbulb

# =============================================================================
# AUTOMATIONS
# =============================================================================
automation:

  # ===========================================================================
  # KITCHEN BUTTON 1 — Bench Downlights (uses helper for state)
  # ===========================================================================
  - id: kitchen_btn1_bench
    alias: "Kitchen — Button 1 (Bench)"
    description: "Toggle bench downlights using helper state"
    triggers:
      - trigger: mqtt
        topic: zigbee2mqtt/kitchen_scene_switch_3g/action
        payload: "1_single"
    actions:
      - choose:
          # If helper says ON → turn OFF
          - conditions:
              - condition: state
                entity_id: input_boolean.kitchen_bench_lights_on
                state: "on"
            sequence:
              - action: input_boolean.turn_off
                target:
                  entity_id: input_boolean.kitchen_bench_lights_on
              - action: light.turn_off
                target:
                  entity_id:
                    - light.kitchen_downlight_bench_hall
                    - light.kitchen_downlight_bench_window
                data:
                  transition: 3
        # If helper says OFF → turn ON
        default:
          - action: input_boolean.turn_on
            target:
              entity_id: input_boolean.kitchen_bench_lights_on
          - action: light.turn_on
            target:
              entity_id:
                - light.kitchen_downlight_bench_hall
                - light.kitchen_downlight_bench_window
            data:
              brightness_pct: 1
              transition: 0
          - delay:
              milliseconds: 150
          - action: light.turn_on
            target:
              entity_id:
                - light.kitchen_downlight_bench_hall
                - light.kitchen_downlight_bench_window
            data:
              color_temp_kelvin: 3000
              transition: 0
          - delay:
              milliseconds: 150
          - action: light.turn_on
            target:
              entity_id:
                - light.kitchen_downlight_bench_hall
                - light.kitchen_downlight_bench_window
            data:
              brightness_pct: 100
              transition: 3
    mode: single

  # ===========================================================================
  # KITCHEN BUTTON 2 — Ceiling Light (Aqara - reliable state)
  # ===========================================================================
  - id: kitchen_btn2_ceiling
    alias: "Kitchen — Button 2 (Ceiling)"
    description: "Toggle ceiling light"
    triggers:
      - trigger: mqtt
        topic: zigbee2mqtt/kitchen_scene_switch_3g/action
        payload: "2_single"
    actions:
      - choose:
          - conditions:
              - condition: or
                conditions:
                  - condition: state
                    entity_id: light.kitchen_ceiling_light_white
                    state: "on"
                  - condition: state
                    entity_id: light.kitchen_ceiling_light_rgb
                    state: "on"
            sequence:
              - action: light.turn_off
                target:
                  entity_id:
                    - light.kitchen_ceiling_light_white
                    - light.kitchen_ceiling_light_rgb
                data:
                  transition: 3
        default:
          - action: light.turn_on
            target:
              entity_id:
                - light.kitchen_ceiling_light_white
                - light.kitchen_ceiling_light_rgb
            data:
              brightness_pct: 100
              color_temp_kelvin: 6535
              transition: 3
    mode: single

  # ===========================================================================
  # KITCHEN BUTTON 3 — Sink Downlight (uses helper for state)
  # ===========================================================================
  - id: kitchen_btn3_sink
    alias: "Kitchen — Button 3 (Sink)"
    description: "Toggle sink downlight using helper state"
    triggers:
      - trigger: mqtt
        topic: zigbee2mqtt/kitchen_scene_switch_3g/action
        payload: "3_single"
    actions:
      - choose:
          # If helper says ON → turn OFF
          - conditions:
              - condition: state
                entity_id: input_boolean.kitchen_sink_light_on
                state: "on"
            sequence:
              - action: input_boolean.turn_off
                target:
                  entity_id: input_boolean.kitchen_sink_light_on
              - action: light.turn_off
                target:
                  entity_id: light.kitchen_downlight_sink
                data:
                  transition: 3
        # If helper says OFF → turn ON
        default:
          - action: input_boolean.turn_on
            target:
              entity_id: input_boolean.kitchen_sink_light_on
          - action: light.turn_on
            target:
              entity_id: light.kitchen_downlight_sink
            data:
              brightness_pct: 1
              transition: 0
          - delay:
              milliseconds: 150
          - action: light.turn_on
            target:
              entity_id: light.kitchen_downlight_sink
            data:
              color_temp_kelvin: 6535
              transition: 0
          - delay:
              milliseconds: 150
          - action: light.turn_on
            target:
              entity_id: light.kitchen_downlight_sink
            data:
              brightness_pct: 100
              transition: 3
    mode: single

  # ===========================================================================
  # SYNC HELPERS ON HA RESTART — Set helpers to match current light state
  # ===========================================================================
  - id: kitchen_helpers_sync_on_start
    alias: "Kitchen — Sync helpers on HA start"
    description: "Reset helpers to OFF on HA restart (safe default)"
    triggers:
      - trigger: homeassistant
        event: start
    actions:
      - action: input_boolean.turn_off
        target:
          entity_id:
            - input_boolean.kitchen_bench_lights_on
            - input_boolean.kitchen_sink_light_on
    mode: single

  # ===========================================================================
  # DINING SINGLE — Toggle
  # ===========================================================================
  - id: dining_single
    alias: "Dining — Single (Toggle)"
    description: "Toggle dining lights"
    triggers:
      - trigger: mqtt
        topic: "zigbee2mqtt/Dining Scene Switch – 1G/action"
        payload: "single"
    actions:
      - choose:
          - conditions:
              - condition: or
                conditions:
                  - condition: state
                    entity_id: light.dining_door_light_white
                    state: "on"
                  - condition: state
                    entity_id: light.dining_hall_light_white
                    state: "on"
                  - condition: state
                    entity_id: light.dining_door_light_rgb
                    state: "on"
                  - condition: state
                    entity_id: light.dining_hall_light_rgb
                    state: "on"
            sequence:
              - action: light.turn_off
                target:
                  entity_id:
                    - light.dining_door_light_white
                    - light.dining_hall_light_white
                    - light.dining_door_light_rgb
                    - light.dining_hall_light_rgb
                data:
                  transition: 3
        default:
          - parallel:
              - action: light.turn_on
                target:
                  entity_id:
                    - light.dining_door_light_white
                    - light.dining_hall_light_white
                data:
                  brightness_pct: 75
                  color_temp_kelvin: 2702
                  transition: 3
              - action: light.turn_on
                target:
                  entity_id:
                    - light.dining_door_light_rgb
                    - light.dining_hall_light_rgb
                data:
                  brightness_pct: 100
                  color_temp_kelvin: 3400
                  transition: 3
    mode: single

  # ===========================================================================
  # DINING DOUBLE — Bright
  # ===========================================================================
  - id: dining_double
    alias: "Dining — Double (Bright)"
    description: "Bright mode"
    triggers:
      - trigger: mqtt
        topic: "zigbee2mqtt/Dining Scene Switch – 1G/action"
        payload: "double"
    actions:
      - parallel:
          - action: light.turn_on
            target:
              entity_id:
                - light.dining_door_light_white
                - light.dining_hall_light_white
            data:
              brightness_pct: 100
              color_temp_kelvin: 3200
              transition: 3
          - action: light.turn_on
            target:
              entity_id:
                - light.dining_door_light_rgb
                - light.dining_hall_light_rgb
            data:
              brightness_pct: 100
              color_temp_kelvin: 3400
              transition: 3
    mode: single

  # ===========================================================================
  # DINING HOLD — Party
  # ===========================================================================
  - id: dining_hold
    alias: "Dining — Hold (Party)"
    description: "Party mode - green rings"
    triggers:
      - trigger: mqtt
        topic: "zigbee2mqtt/Dining Scene Switch – 1G/action"
        payload: "hold"
      - trigger: mqtt
        topic: "zigbee2mqtt/Dining Scene Switch – 1G/action"
        payload: "long"
    actions:
      - parallel:
          - action: light.turn_on
            target:
              entity_id:
                - light.dining_door_light_white
                - light.dining_hall_light_white
            data:
              brightness_pct: 100
              color_temp_kelvin: 2702
              transition: 3
          - action: light.turn_on
            target:
              entity_id:
                - light.dining_door_light_rgb
                - light.dining_hall_light_rgb
            data:
              brightness_pct: 100
              rgb_color: [0, 255, 0]
              transition: 3
    mode: single
